export const MOSTRAR_PELICULAS = "MOSTRAR_PELICULAS";
export const GUARDAR_FAVORITO = "GUARDAR_FAVORITO";
export const ELIMINAR_FAVORITO = "ELIMINAR_FAVORITO";
export const LOADINGFAV = "LOADINGFAV";
export const GUARDAR_FOTO = "GUARDAR_FOTO";

export const LOADING = "LOADING";
export const ERROR = "ERROR"